--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Cosmoverse/mcMMO
build-by-default: true
branches:
- master
projects:
  mcMMO:
    path: ""
    lint:
      phpstan: false
    libs:
      - src: poggit/libasynql/libasynql
        version: ^4.1.1
        branch: pm5
...
